package sections

var dhcpModes = []string{"server", "relay", "hybrid", "disabled"}

var dhcp = []Spec{
	{
		Name: "dhcp_dnsmasq", Config: "dhcp", Type: "dnsmasq", Singleton: true,
		Description: "The dnsmasq DNS/DHCP server instance (`config dnsmasq`).",
		Options: []Option{
			flag("domainneeded", "Never forward plain names."),
			flag("boguspriv", "Never forward reverse lookups for private ranges."),
			flag("filterwin2k", "Filter useless Windows-originated queries."),
			flag("localise_queries", "Answer with the address of the receiving interface."),
			flag("rebind_protection", "Discard upstream RFC1918 answers."),
			flag("rebind_localhost", "Allow upstream 127.0.0.0/8 answers."),
			list("rebind_domain", "Domains allowed to return private addresses."),
			str("local", "Local-only domain, e.g. `/lan/`."),
			str("domain", "Local DNS domain."),
			flag("expandhosts", "Add the local domain to hostnames from hosts files."),
			flag("nonegcache", "Do not cache negative replies."),
			num("cachesize", "DNS cache size."),
			flag("authoritative", "Authoritative DHCP server."),
			flag("readethers", "Read /etc/ethers."),
			str("leasefile", "Lease file path."),
			str("resolvfile", "Upstream resolv file."),
			flag("noresolv", "Do not read the resolv file."),
			flag("nonwildcard", "Bind only to configured interfaces."),
			flag("localservice", "Only answer queries from local subnets."),
			num("ednspacket_max", "Maximum EDNS packet size."),
			flag("filter_aaaa", "Remove AAAA records from answers."),
			flag("filter_a", "Remove A records from answers."),
			list("server", "Upstream servers (`/domain/ip` syntax supported)."),
			list("address", "Static answers `/domain/ip`."),
			list("ipset", "Populate ipsets `/domain/set`."),
			list("interface", "Listen only on these interfaces."),
			list("notinterface", "Never listen on these interfaces."),
			list("addnhosts", "Extra hosts files."),
			flag("logqueries", "Log DNS queries."),
			flag("dnssec", "Validate DNSSEC."),
			flag("dnsseccheckunsigned", "Check unsigned replies for DNSSEC."),
			flag("strictorder", "Query upstream servers in order."),
			flag("allservers", "Query all upstream servers."),
			flag("sequential_ip", "Allocate addresses sequentially."),
			num("port", "DNS listen port (0 disables DNS)."),
			num("dhcpleasemax", "Maximum number of leases."),
			flag("quietdhcp", "Suppress DHCP logging."),
			flag("localuse", "Use dnsmasq as the router's own resolver."),
			str("confdir", "Extra configuration directory."),
		},
	},
	{
		Name: "dhcp_pool", Config: "dhcp", Type: "dhcp",
		Description: "DHCP/RA settings for one interface (`config dhcp`).",
		Options: []Option{
			required(str("interface", "Logical interface.")),
			num("start", "Offset of the first leased address."),
			num("limit", "Number of leasable addresses."),
			str("leasetime", "Lease time, e.g. `12h`."),
			flag("ignore", "Do not serve DHCPv4 on this interface."),
			flag("force", "Serve even if another DHCP server is detected."),
			enum("dhcpv4", "DHCPv4 mode (odhcpd).", "server", "disabled"),
			enum("dhcpv6", "DHCPv6 mode.", dhcpModes...),
			enum("ra", "Router advertisement mode.", dhcpModes...),
			enum("ndp", "NDP proxy mode.", "relay", "hybrid", "disabled"),
			list("ra_flags", "RA flags: `managed-config`, `other-config`, `home-agent`, `none`."),
			num("ra_default", "Announce default route: 0 auto, 1 without public prefix, 2 always."),
			flag("ra_slaac", "Announce SLAAC prefixes."),
			flag("master", "Master interface for relaying."),
			list("dhcp_option", "Extra DHCP options, e.g. `6,192.168.1.1`."),
			list("dhcp_option_force", "DHCP options sent even when not requested."),
			list("dns", "DNS servers announced via DHCPv6/RA."),
			list("domain", "Search domains announced via DHCPv6/RA."),
			flag("dns_service", "Announce the router as DNS server."),
			str("networkid", "dnsmasq network id / tag."),
			list("tag", "Tags for this pool."),
			str("netmask", "Netmask override."),
			str("instance", "dnsmasq instance."),
			str("preferred_lifetime", "Preferred lifetime for DHCPv6/RA."),
			str("max_preferred_lifetime", "Maximum preferred lifetime."),
		},
	},
	{
		Name: "dhcp_host", Config: "dhcp", Type: "host",
		Description: "A static DHCP lease (`config host`).",
		Options: []Option{
			str("name", "Hostname."),
			list("mac", "MAC addresses."),
			str("ip", "IPv4 address, or `ignore`."),
			str("hostid", "IPv6 host id (hex)."),
			list("duid", "DHCPv6 DUIDs."),
			str("leasetime", "Lease time override."),
			list("tag", "Tags to set."),
			flag("dns", "Add a DNS entry for the host."),
			flag("broadcast", "Force broadcast replies."),
			str("instance", "dnsmasq instance."),
		},
	},
	{
		Name: "dhcp_domain", Config: "dhcp", Type: "domain",
		Description: "A static DNS A/AAAA record (`config domain`).",
		Options: []Option{
			required(str("name", "Hostname.")),
			required(str("ip", "Address.")),
		},
	},
	{
		Name: "dhcp_cname", Config: "dhcp", Type: "cname",
		Description: "A DNS CNAME record (`config cname`).",
		Options: []Option{
			required(str("cname", "Alias name.")),
			required(str("target", "Target name.")),
		},
	},
	{
		Name: "dhcp_srv", Config: "dhcp", Type: "srvhost",
		Description: "A DNS SRV record (`config srvhost`).",
		Options: []Option{
			required(str("srv", "Service name, e.g. `_sip._tcp.example.lan`.")),
			required(str("target", "Target host.")),
			num("port", "Port."),
			num("class", "Priority."),
			num("weight", "Weight."),
		},
	},
	{
		Name: "dhcp_mx", Config: "dhcp", Type: "mxhost",
		Description: "A DNS MX record (`config mxhost`).",
		Options: []Option{
			required(str("domain", "Mail domain.")),
			required(str("relay", "Mail relay host.")),
			num("pref", "Preference."),
		},
	},
	{
		Name: "dhcp_boot", Config: "dhcp", Type: "boot",
		Description: "A network boot (PXE) entry (`config boot`).",
		Options: []Option{
			required(str("filename", "Boot file name.")),
			str("servername", "Boot server name."),
			str("serveraddress", "Boot server address."),
			str("networkid", "Only for this network id/tag."),
			flag("force", "Always send the options."),
			list("dhcp_option", "Extra DHCP options."),
		},
	},
	{
		Name: "dhcp_tag", Config: "dhcp", Type: "tag",
		Description: "DHCP options for clients with a tag (`config tag`).",
		Options: []Option{
			list("dhcp_option", "DHCP options."),
			flag("force", "Always send the options."),
		},
	},
	{
		Name: "dhcp_odhcpd", Config: "dhcp", Type: "odhcpd", Singleton: true,
		Description: "odhcpd daemon settings (`config odhcpd`).",
		Options: []Option{
			flag("maindhcp", "Use odhcpd as the DHCPv4 server."),
			str("leasefile", "Lease file path."),
			str("leasetrigger", "Script run on lease changes."),
			num("loglevel", "Syslog level."),
			str("piofolder", "Directory for prefix information persistence."),
			str("hostsdir", "Directory for generated hosts files."),
		},
	},
}
