package sections

var families = []string{"ipv4", "ipv6", "any"}

var firewall = []Spec{
	{
		Name: "firewall_defaults", Config: "firewall", Type: "defaults", Singleton: true,
		Description: "Global firewall defaults (`config defaults`).",
		Options: []Option{
			enum("input", "Default input policy.", policies...),
			enum("output", "Default output policy.", policies...),
			enum("forward", "Default forward policy.", policies...),
			flag("syn_flood", "Enable SYN flood protection (legacy name)."),
			flag("synflood_protect", "Enable SYN flood protection."),
			flag("drop_invalid", "Drop invalid packets."),
			flag("flow_offloading", "Software flow offloading."),
			flag("flow_offloading_hw", "Hardware flow offloading."),
			flag("tcp_syncookies", "Enable TCP SYN cookies."),
			num("tcp_ecn", "TCP ECN: 0 off, 1 on, 2 when requested."),
			flag("tcp_window_scaling", "Enable TCP window scaling."),
			flag("accept_redirects", "Accept ICMP redirects."),
			flag("accept_source_route", "Accept source-routed packets."),
			flag("custom_chains", "Create custom user chains (fw3)."),
			flag("disable_ipv6", "Disable IPv6 firewall rules."),
			flag("auto_helper", "Automatically assign conntrack helpers."),
			flag("auto_includes", "Load /etc/nftables.d includes (fw4)."),
		},
	},
	{
		Name: "firewall_zone", Config: "firewall", Type: "zone",
		Description: "A firewall zone (`config zone`).",
		Options: []Option{
			required(str("name", "Zone name, referenced by forwardings and rules.")),
			list("network", "Logical interfaces in the zone."),
			list("device", "Raw devices in the zone."),
			list("subnet", "Subnets in the zone."),
			enum("input", "Input policy.", policies...),
			enum("output", "Output policy.", policies...),
			enum("forward", "Forward policy.", policies...),
			flag("masq", "Enable IPv4 masquerading."),
			flag("masq6", "Enable IPv6 masquerading."),
			list("masq_src", "Limit masquerading to these source subnets."),
			list("masq_dest", "Limit masquerading to these destination subnets."),
			flag("mtu_fix", "Enable MSS clamping."),
			enum("family", "Address family.", families...),
			flag("conntrack", "Force connection tracking."),
			num("log", "Log rejected/dropped traffic (bitmask on fw4)."),
			str("log_limit", "Log rate limit, e.g. `10/minute`."),
			flag("auto_helper", "Automatically assign conntrack helpers."),
			list("helper", "Conntrack helpers."),
			str("extra_src", "Extra match arguments for source rules."),
			str("extra_dest", "Extra match arguments for destination rules."),
			flag("enabled", "Enable the zone."),
		},
	},
	{
		Name: "firewall_forwarding", Config: "firewall", Type: "forwarding",
		Description: "Allowed forwarding between two zones (`config forwarding`).",
		Options: []Option{
			required(str("src", "Source zone.")),
			required(str("dest", "Destination zone.")),
			str("name", "Descriptive name."),
			enum("family", "Address family.", families...),
			str("ipset", "Match an ipset."),
			flag("enabled", "Enable the forwarding."),
		},
	},
	{
		Name: "firewall_rule", Config: "firewall", Type: "rule",
		Description: "A traffic rule (`config rule`). Use `openwrt_uci_order` when rule order matters.",
		Options: append([]Option{
			str("name", "Descriptive name."),
			str("src", "Source zone (`*` for any)."),
			list("src_ip", "Source addresses."),
			list("src_mac", "Source MAC addresses."),
			str("src_port", "Source ports."),
			str("dest", "Destination zone (`*` for any, empty for input)."),
			list("dest_ip", "Destination addresses."),
			str("dest_port", "Destination ports."),
			list("proto", "Protocols (`tcp`, `udp`, `icmp`, `all`, ...)."),
			list("icmp_type", "ICMP types."),
			enum("family", "Address family.", families...),
			enum("target", "Action.", "ACCEPT", "REJECT", "DROP", "MARK", "NOTRACK", "HELPER", "DSCP"),
			str("mark", "Match firewall mark."),
			str("set_mark", "MARK target: set mark."),
			str("set_xmark", "MARK target: xor mark."),
			str("set_dscp", "DSCP target: value."),
			str("set_helper", "HELPER target: helper."),
			str("device", "Match device."),
			enum("direction", "Direction for `device`.", "in", "out"),
			str("start_date", "Start date `YYYY-MM-DD`."),
			str("stop_date", "Stop date `YYYY-MM-DD`."),
			str("start_time", "Start time `hh:mm:ss`."),
			str("stop_time", "Stop time `hh:mm:ss`."),
			str("weekdays", "Weekdays, e.g. `Mon Tue`."),
			str("monthdays", "Days of month."),
			flag("utc_time", "Times are UTC."),
		}, matchCommon()...),
	},
	{
		Name: "firewall_redirect", Config: "firewall", Type: "redirect",
		Description: "A port forward / NAT redirect (`config redirect`).",
		Options: append([]Option{
			str("name", "Descriptive name."),
			str("src", "Source zone."),
			str("src_ip", "Source address."),
			str("src_dip", "Original destination address (DNAT) / rewritten source (SNAT)."),
			str("src_mac", "Source MAC address."),
			str("src_port", "Source port."),
			str("src_dport", "Original destination port."),
			str("dest", "Destination zone."),
			str("dest_ip", "Internal destination address."),
			str("dest_port", "Internal destination port."),
			list("proto", "Protocols."),
			enum("target", "NAT type.", "DNAT", "SNAT"),
			enum("family", "Address family.", families...),
			flag("reflection", "Enable NAT loopback."),
			enum("reflection_src", "Reflection source address.", "internal", "external"),
			list("reflection_zone", "Zones to reflect into."),
			str("mark", "Match firewall mark."),
			str("helper", "Conntrack helper."),
		}, matchCommon()...),
	},
	{
		Name: "firewall_nat", Config: "firewall", Type: "nat",
		Description: "A source NAT rule (`config nat`, fw4).",
		Options: append([]Option{
			str("name", "Descriptive name."),
			str("src", "Zone the traffic leaves through."),
			str("src_ip", "Source address."),
			str("src_port", "Source port."),
			str("dest_ip", "Destination address."),
			str("dest_port", "Destination port."),
			list("proto", "Protocols."),
			enum("target", "Action.", "SNAT", "MASQUERADE", "ACCEPT"),
			str("snat_ip", "SNAT address."),
			str("snat_port", "SNAT port."),
			enum("family", "Address family.", families...),
			str("device", "Outgoing device."),
			str("mark", "Match firewall mark."),
		}, matchCommon()...),
	},
	{
		Name: "firewall_ipset", Config: "firewall", Type: "ipset",
		Description: "A named set (`config ipset`).",
		Options: []Option{
			required(str("name", "Set name.")),
			enum("family", "Address family.", "ipv4", "ipv6"),
			list("match", "Match fields, e.g. `src_ip`, `dest_port`."),
			list("entry", "Set entries."),
			str("loadfile", "File with entries."),
			num("timeout", "Entry timeout."),
			num("maxelem", "Maximum number of elements."),
			flag("counters", "Enable counters."),
			str("comment", "Comment."),
			flag("enabled", "Enable the set."),
		},
	},
	{
		Name: "firewall_include", Config: "firewall", Type: "include",
		Description: "An include of a script or nftables snippet (`config include`).",
		Options: []Option{
			required(str("path", "Path of the include on the router.")),
			enum("type", "Include type.", "script", "nftables", "restore"),
			enum("position", "nftables include position.", "ruleset-pre", "ruleset-post", "table-pre", "table-post", "chain-pre", "chain-post"),
			str("chain", "Chain for chain-pre/chain-post."),
			flag("fw4_compatible", "Script is fw4 compatible."),
			flag("reload", "Re-run on firewall reload."),
			flag("enabled", "Enable the include."),
		},
	},
}

func matchCommon() []Option {
	return []Option{
		str("ipset", "Match an ipset (`!` to negate)."),
		str("limit", "Rate limit, e.g. `10/second`."),
		num("limit_burst", "Rate limit burst."),
		str("extra", "Extra raw match arguments."),
		flag("enabled", "Enable the rule."),
	}
}
