package sections

var policies = []string{"ACCEPT", "REJECT", "DROP"}

var network = []Spec{
	{
		Name: "network_interface", Config: "network", Type: "interface",
		Description: "A logical network interface (`config interface` in /etc/config/network).",
		Options: []Option{
			required(str("proto", "Protocol: static, dhcp, dhcpv6, pppoe, wireguard, none, ...")),
			str("device", "Underlying device, e.g. `br-lan` or `wan`."),
			flag("auto", "Bring up on boot."),
			flag("disabled", "Disable the interface."),
			flag("force_link", "Keep addresses and routes even when the link is down."),
			flag("ipv6", "Enable IPv6 on the interface."),
			num("mtu", "MTU override."),
			num("metric", "Default route metric."),
			str("macaddr", "MAC address override."),
			str("ipaddr", "IPv4 address (static)."),
			str("netmask", "IPv4 netmask (static)."),
			str("gateway", "IPv4 default gateway (static)."),
			str("broadcast", "IPv4 broadcast address."),
			list("ip6addr", "IPv6 addresses in CIDR notation."),
			str("ip6gw", "IPv6 default gateway."),
			num("ip6assign", "Delegate a prefix of this length to the interface."),
			str("ip6hint", "Sub-prefix ID hint for the delegated prefix."),
			list("ip6class", "Allowed prefix classes for delegation."),
			str("ip6ifaceid", "IPv6 interface identifier."),
			flag("delegate", "Enable prefix delegation to downstream interfaces."),
			list("dns", "Static DNS servers."),
			list("dns_search", "DNS search domains."),
			flag("peerdns", "Use DNS servers announced by the peer."),
			flag("defaultroute", "Install a default route from DHCP/PPP."),
			str("hostname", "Hostname sent in DHCP requests (`*` = system hostname)."),
			str("clientid", "DHCP client identifier."),
			str("vendorid", "DHCP vendor class."),
			enum("reqaddress", "DHCPv6 address request mode.", "try", "force", "none"),
			str("reqprefix", "DHCPv6 requested prefix length, `auto` or `no`."),
			flag("norelease", "Do not send DHCP release on shutdown."),
			str("username", "PPP username."),
			secret("password", "PPP password."),
			str("service", "PPPoE service name / 3G service type."),
			str("ac", "PPPoE access concentrator."),
			str("keepalive", "PPP LCP echo `failures interval`."),
			secret("private_key", "WireGuard private key."),
			num("listen_port", "WireGuard listen port."),
			list("addresses", "WireGuard interface addresses."),
			str("fwmark", "WireGuard firewall mark."),
			flag("nohostroute", "WireGuard: do not add routes to peer endpoints."),
			str("ip4table", "Routing table for IPv4 routes of this interface."),
			str("ip6table", "Routing table for IPv6 routes of this interface."),
		},
	},
	{
		Name: "network_device", Config: "network", Type: "device",
		Description: "A layer-2 device such as a bridge or VLAN (`config device`).",
		Options: []Option{
			required(str("name", "Device name, e.g. `br-lan`.")),
			enum("type", "Device type (empty for a plain device override).", "bridge", "8021q", "8021ad", "macvlan", "veth"),
			list("ports", "Bridge member ports."),
			str("ifname", "Base device for VLAN/macvlan."),
			num("vid", "VLAN ID for 8021q/8021ad devices."),
			str("macaddr", "MAC address override."),
			num("mtu", "MTU."),
			num("txqueuelen", "TX queue length."),
			flag("ipv6", "Enable IPv6 on the device."),
			flag("promisc", "Promiscuous mode."),
			flag("stp", "Bridge: enable spanning tree."),
			flag("igmp_snooping", "Bridge: enable IGMP snooping."),
			flag("bridge_empty", "Bridge: create even without ports."),
			flag("vlan_filtering", "Bridge: enable VLAN filtering."),
		},
	},
	{
		Name: "network_bridge_vlan", Config: "network", Type: "bridge-vlan",
		Description: "A VLAN on a VLAN-filtering bridge (`config bridge-vlan`).",
		Options: []Option{
			required(str("device", "Bridge device name.")),
			required(num("vlan", "VLAN ID.")),
			list("ports", "Member ports, optionally suffixed `:t`, `:u`, `:*`."),
			flag("local", "Also add the VLAN to the bridge itself."),
		},
	},
	routeSpec("network_route", "route", "IPv4"),
	routeSpec("network_route6", "route6", "IPv6"),
	ruleSpec("network_rule", "rule", "IPv4"),
	ruleSpec("network_rule6", "rule6", "IPv6"),
	{
		Name: "network_globals", Config: "network", Type: "globals", Singleton: true,
		Description: "Global network options (`config globals`).",
		Options: []Option{
			str("ula_prefix", "IPv6 ULA prefix."),
			num("packet_steering", "Packet steering: 0 off, 1 on, 2 all CPUs."),
			num("steering_flows", "Number of RPS flows."),
			flag("tcp_l3mdev", "Allow TCP sockets in VRFs."),
			flag("udp_l3mdev", "Allow UDP sockets in VRFs."),
		},
	},
	{
		Name: "network_wireguard_peer", Config: "network", Type: "wireguard_",
		TypeFrom: "interface", TypeFromDesc: "WireGuard interface the peer belongs to (section type becomes `wireguard_<interface>`).",
		Description: "A WireGuard peer (`config wireguard_<interface>`).",
		Options: []Option{
			required(str("public_key", "Peer public key.")),
			secret("preshared_key", "Optional preshared key."),
			list("allowed_ips", "Allowed IPs in CIDR notation."),
			flag("route_allowed_ips", "Create routes for allowed IPs."),
			str("endpoint_host", "Peer endpoint host."),
			num("endpoint_port", "Peer endpoint port."),
			num("persistent_keepalive", "Keepalive interval in seconds."),
			str("description", "Free-form description."),
			flag("disabled", "Disable the peer."),
		},
	},
}

func routeSpec(name, typ, family string) Spec {
	return Spec{
		Name: name, Config: "network", Type: typ,
		Description: "A static " + family + " route (`config " + typ + "`).",
		Options: []Option{
			required(str("interface", "Logical interface the route belongs to.")),
			required(str("target", "Destination network (CIDR or address).")),
			str("netmask", "Netmask when target is not in CIDR notation."),
			str("gateway", "Next hop."),
			num("metric", "Route metric."),
			num("mtu", "Route MTU."),
			str("table", "Routing table."),
			str("source", "Preferred source address."),
			flag("onlink", "Gateway is on-link."),
			enum("type", "Route type.", "unicast", "local", "broadcast", "multicast", "unreachable", "prohibit", "blackhole", "anycast", "throw"),
			flag("disabled", "Disable the route."),
		},
	}
}

func ruleSpec(name, typ, family string) Spec {
	return Spec{
		Name: name, Config: "network", Type: typ,
		Description: "An " + family + " policy routing rule (`config " + typ + "`).",
		Options: []Option{
			str("in", "Incoming logical interface."),
			str("out", "Outgoing logical interface."),
			str("src", "Source subnet."),
			str("dest", "Destination subnet."),
			num("tos", "TOS value."),
			str("mark", "Firewall mark (`mark/mask`)."),
			flag("invert", "Invert the match."),
			num("priority", "Rule priority."),
			str("lookup", "Routing table to look up."),
			num("goto", "Jump to the rule with this priority."),
			enum("action", "Rule action.", "prohibit", "unreachable", "blackhole", "throw"),
			num("suppress_prefixlength", "Reject routing decisions with this prefix length or less."),
			str("uidrange", "UID range `start-end`."),
			str("ipproto", "IP protocol."),
			flag("disabled", "Disable the rule."),
		},
	}
}
