package sections

var system = []Spec{
	{
		Name: "system", Config: "system", Type: "system", Singleton: true,
		Description: "Core system settings (`config system`).",
		Options: []Option{
			str("hostname", "Hostname."),
			str("description", "Short description shown in LuCI."),
			str("notes", "Free-form notes."),
			str("timezone", "POSIX TZ string, e.g. `CET-1CEST,M3.5.0,M10.5.0/3`."),
			str("zonename", "Olson zone name, e.g. `Europe/London`."),
			num("log_size", "Size of the in-memory log in KiB."),
			num("log_buffer_size", "Kernel log buffer size in KiB."),
			str("log_file", "Persistent log file."),
			str("log_ip", "Remote syslog server."),
			num("log_port", "Remote syslog port."),
			enum("log_proto", "Remote syslog protocol.", "udp", "tcp"),
			flag("log_remote", "Enable remote logging."),
			num("conloglevel", "Console log level."),
			num("klogconloglevel", "Kernel console log level."),
			num("cronloglevel", "Cron log level."),
			flag("urandom_seed", "Save a random seed across reboots."),
			flag("ttylogin", "Require login on the serial console."),
		},
	},
	{
		Name: "system_ntp", Config: "system", Type: "timeserver", Singleton: true,
		Description: "NTP client/server settings (`config timeserver`, usually named `ntp`).",
		Options: []Option{
			flag("enabled", "Enable the NTP client."),
			flag("enable_server", "Serve NTP to the LAN."),
			list("server", "NTP servers."),
			flag("use_dhcp", "Use NTP servers announced via DHCP."),
			str("interface", "Interface to serve NTP on."),
		},
	},
	{
		Name: "system_led", Config: "system", Type: "led",
		Description: "An LED trigger (`config led`).",
		Options: []Option{
			str("name", "Descriptive name."),
			required(str("sysfs", "LED name under /sys/class/leds.")),
			str("trigger", "Trigger: `none`, `default-on`, `timer`, `netdev`, `heartbeat`, ..."),
			flag("default", "Initial state."),
			str("dev", "netdev trigger: device."),
			str("mode", "netdev trigger: modes, e.g. `link tx rx`."),
			num("delayon", "timer trigger: on time in ms."),
			num("delayoff", "timer trigger: off time in ms."),
			flag("inverted", "Invert the LED."),
		},
	},
}

var services = []Spec{
	{
		Name: "dropbear", Config: "dropbear", Type: "dropbear", Singleton: true,
		Description: "The dropbear SSH server instance (`config dropbear`).",
		Options: []Option{
			flag("enable", "Enable this instance."),
			num("Port", "Listen port."),
			str("Interface", "Listen only on this logical interface."),
			notSecret(flag("PasswordAuth", "Allow password logins.")),
			notSecret(flag("RootPasswordAuth", "Allow root password logins.")),
			flag("RootLogin", "Allow root logins."),
			flag("GatewayPorts", "Allow remote hosts to connect to forwarded ports."),
			str("BannerFile", "Banner shown before login."),
			num("IdleTimeout", "Idle timeout in seconds."),
			num("MaxAuthTries", "Maximum authentication attempts."),
			num("SSHKeepAlive", "Keepalive interval in seconds."),
			notSecret(list("keyfile", "Host key files.")),
		},
	},
	{
		Name: "uhttpd", Config: "uhttpd", Type: "uhttpd", Singleton: true,
		Description: "The uhttpd web server instance serving LuCI and /ubus (`config uhttpd`). Changes here can cut the provider off; rollback protects against that.",
		Options: []Option{
			list("listen_http", "HTTP listen addresses."),
			list("listen_https", "HTTPS listen addresses."),
			str("home", "Document root."),
			notSecret(str("cert", "TLS certificate file.")),
			notSecret(str("key", "TLS private key file (a path, not the key).")),
			flag("redirect_https", "Redirect HTTP to HTTPS."),
			flag("rfc1918_filter", "Reject requests from public IPs to private addresses."),
			num("max_requests", "Maximum concurrent requests."),
			num("max_connections", "Maximum concurrent connections."),
			str("cgi_prefix", "CGI prefix."),
			list("lua_prefix", "Lua handler prefixes."),
			list("ucode_prefix", "ucode handler prefixes."),
			str("ubus_prefix", "ubus JSON-RPC prefix (the provider needs this, normally `/ubus`)."),
			flag("ubus_cors", "Enable CORS for ubus."),
			num("script_timeout", "Script timeout in seconds."),
			num("network_timeout", "Network timeout in seconds."),
			num("http_keepalive", "HTTP keepalive timeout."),
			flag("tcp_keepalive", "Enable TCP keepalive."),
			flag("no_dirlists", "Disable directory listings."),
			list("index_page", "Index pages."),
			str("error_page", "Error page handler."),
		},
	},
	{
		Name: "uhttpd_cert", Config: "uhttpd", Type: "cert", Singleton: true,
		Description: "Parameters for uhttpd's self-signed certificate (`config cert`).",
		Options: []Option{
			num("days", "Validity in days."),
			notSecret(enum("key_type", "Key type.", "rsa", "ec")),
			num("bits", "RSA key size."),
			str("ec_curve", "EC curve."),
			str("country", "Country."),
			str("state", "State."),
			str("location", "Location."),
			str("commonname", "Common name."),
			str("organization", "Organization."),
		},
	},
	{
		Name: "rpcd", Config: "rpcd", Type: "rpcd", Singleton: true,
		Description: "rpcd daemon settings (`config rpcd`).",
		Options: []Option{
			str("socket", "ubus socket path."),
			num("timeout", "Call timeout in seconds."),
		},
	},
	{
		Name: "rpcd_login", Config: "rpcd", Type: "login",
		Description: "An rpcd/LuCI login and its ACL groups (`config login`). The provider itself authenticates with one of these.",
		Options: []Option{
			required(str("username", "Login name.")),
			secret("password", "`$p$<user>` to use the system password, or a crypt hash (`$1$...`)."),
			list("read", "ACL groups with read access (`*` for all)."),
			list("write", "ACL groups with write access (`*` for all)."),
			num("timeout", "Session timeout in seconds."),
		},
	},
	{
		Name: "sqm_queue", Config: "sqm", Type: "queue",
		Description: "An SQM smart queue (`config queue`, package sqm-scripts).",
		Options: []Option{
			flag("enabled", "Enable the queue."),
			required(str("interface", "Device to shape, e.g. `wan`.")),
			num("download", "Download rate in kbit/s (0 disables ingress shaping)."),
			num("upload", "Upload rate in kbit/s."),
			str("qdisc", "Queue discipline, e.g. `cake`."),
			str("script", "Shaper script, e.g. `piece_of_cake.qos`."),
			enum("linklayer", "Link layer adaptation.", "none", "ethernet", "atm"),
			num("overhead", "Per-packet overhead in bytes."),
			flag("qdisc_advanced", "Enable advanced qdisc options."),
			str("ingress_ecn", "Ingress ECN: `ECN` or `NOECN`."),
			str("egress_ecn", "Egress ECN: `ECN` or `NOECN`."),
			flag("squash_dscp", "Squash DSCP on ingress."),
			flag("squash_ingress", "Ignore DSCP on ingress."),
			flag("debug_logging", "Enable debug logging."),
			num("verbosity", "Log verbosity."),
		},
	},
	{
		Name: "qos_interface", Config: "qos", Type: "interface",
		Description: "qos-scripts shaping for one interface (`config interface`).",
		Options: []Option{
			flag("enabled", "Enable shaping."),
			str("classgroup", "Class group to use."),
			flag("overhead", "Account for protocol overhead."),
			num("download", "Download rate in kbit/s."),
			num("upload", "Upload rate in kbit/s."),
		},
	},
	qosClassify("qos_classify", "classify", "A qos-scripts classification rule (`config classify`)."),
	qosClassify("qos_default", "default", "A qos-scripts default rule (`config default`)."),
	qosClassify("qos_reclassify", "reclassify", "A qos-scripts reclassification rule (`config reclassify`)."),
	{
		Name: "qos_class", Config: "qos", Type: "class",
		Description: "A qos-scripts traffic class (`config class`).",
		Options: []Option{
			num("packetsize", "Average packet size."),
			num("packetdelay", "Packet delay in ms."),
			num("maxsize", "Maximum packet size."),
			num("avgrate", "Average rate in percent."),
			num("limitrate", "Rate limit in percent."),
			num("maxdelay", "Maximum delay in ms."),
			num("priority", "Priority."),
		},
	},
	{
		Name: "qos_classgroup", Config: "qos", Type: "classgroup",
		Description: "A qos-scripts class group (`config classgroup`).",
		Options: []Option{
			str("classes", "Space-separated class names."),
			str("default", "Default class."),
		},
	},
}

func qosClassify(name, typ, desc string) Spec {
	return Spec{
		Name: name, Config: "qos", Type: typ, Description: desc,
		Options: []Option{
			required(str("target", "Target class.")),
			str("proto", "Protocol."),
			str("srchost", "Source host."),
			str("dsthost", "Destination host."),
			str("ports", "Ports."),
			str("srcports", "Source ports."),
			str("dstports", "Destination ports."),
			str("portrange", "Port range."),
			str("pktsize", "Packet size."),
			str("tcpflags", "TCP flags."),
			str("mark", "Mark."),
			str("connbytes", "Connection bytes."),
			str("dscp", "DSCP."),
			str("direction", "Direction."),
			str("comment", "Comment."),
		},
	}
}
