package sections

var wireless = []Spec{
	{
		Name: "wireless_device", Config: "wireless", Type: "wifi-device", Singleton: true,
		Description: "A radio (`config wifi-device`). Radios are detected by the router, so this resource adopts an existing section and never deletes it.",
		Options: []Option{
			str("type", "Driver type, normally `mac80211`."),
			str("path", "Device path of the radio."),
			enum("band", "Band.", "2g", "5g", "6g", "60g"),
			str("channel", "Channel number or `auto`."),
			list("channels", "Channels allowed for automatic selection."),
			str("htmode", "HT/VHT/HE/EHT mode, e.g. `HE80`."),
			str("country", "ISO/IEC 3166 alpha-2 country code."),
			num("cell_density", "Cell density: 0 disabled, 1 normal, 2 high, 3 very high."),
			num("txpower", "Transmit power in dBm."),
			flag("disabled", "Disable the radio."),
			flag("legacy_rates", "Allow legacy 802.11b rates."),
			flag("noscan", "Do not scan for overlapping BSSs (forces 40MHz)."),
			num("beacon_int", "Beacon interval in TUs."),
			num("distance", "Distance to the farthest station in meters."),
			num("rts", "RTS/CTS threshold."),
			num("log_level", "hostapd log level."),
			flag("acs_exclude_dfs", "Exclude DFS channels from automatic selection."),
		},
	},
	{
		Name: "wireless_iface", Config: "wireless", Type: "wifi-iface",
		Description: "A wireless network on a radio (`config wifi-iface`).",
		Options: []Option{
			required(str("device", "Radio section name, e.g. `radio0`.")),
			required(enum("mode", "Operating mode.", "ap", "sta", "adhoc", "mesh", "monitor", "wds")),
			list("network", "Logical interfaces to attach to."),
			str("ssid", "SSID."),
			str("bssid", "BSSID override (or target BSSID in sta mode)."),
			str("ifname", "Interface name override."),
			str("macaddr", "MAC address override or `random`."),
			str("encryption", "Encryption, e.g. `psk2`, `sae`, `sae-mixed`, `owe`, `wpa2`, `none`."),
			secret("key", "WPA passphrase or PSK."),
			secret("sae_password", "WPA3-SAE password when it differs from `key`."),
			flag("hidden", "Do not broadcast the SSID."),
			flag("isolate", "Isolate clients from each other."),
			flag("disabled", "Disable this network."),
			flag("wmm", "Enable WMM."),
			flag("wds", "Enable 4-address (WDS) mode."),
			enum("macfilter", "MAC filter policy.", "disable", "allow", "deny"),
			list("maclist", "MAC addresses for the filter."),
			flag("ieee80211r", "Enable 802.11r fast transition."),
			str("mobility_domain", "802.11r mobility domain."),
			flag("ft_over_ds", "802.11r: FT over DS."),
			flag("ft_psk_generate_local", "802.11r: generate PMK-R0/R1 locally."),
			num("ieee80211w", "802.11w management frame protection: 0, 1 optional, 2 required."),
			flag("ieee80211k", "Enable 802.11k radio resource management."),
			flag("bss_transition", "Enable 802.11v BSS transition."),
			num("ocv", "Operating channel validation."),
			num("dtim_period", "DTIM period."),
			num("max_inactivity", "Station inactivity timeout."),
			flag("disassoc_low_ack", "Disassociate stations on low ACK."),
			num("multi_ap", "Multi-AP mode."),
			str("auth_server", "RADIUS authentication server."),
			num("auth_port", "RADIUS authentication port."),
			secret("auth_secret", "RADIUS shared secret."),
			num("dynamic_vlan", "RADIUS dynamic VLAN: 0 off, 1 optional, 2 required."),
			str("mesh_id", "Mesh ID (mesh mode)."),
			flag("mesh_fwding", "Enable mesh forwarding."),
		},
	},
}
